spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8
server:
  port: 8443
  ssl:
    key-store: classpath:2287197_www.cduhw.cn.pfx
    key-store-type: PKCS12
    key-store-password: 0kA5mHuj
    #    证书路径
#    key-store: classpath:tomcat.key
#    key-store-type: JKS
#    key-alias: tomcat
#    #    配置密码，就是在生成证书的时候输入的密码
#    key-store-password: klklkl

logging:
  level:
    root:  INFO
    org.springframework:  INFO
    org.mybatis:  INFO
    org.linlinjava.litemall.core:  INFO
    org.linlinjava.litemall.db:  INFO
    org.linlinjava.litemall.admin:  INFO
    org.linlinjava.litemall.wx:  INFO
    org.linlinjava.litemall:  INFO

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
